version: '3.8'

services:
  # Chatbot Backend
  app:
    build: .
    container_name: chatbot_app
    restart: always
    ports:
      - "8000:8000"
    environment:
      - WHATSAPP_API_URL=http://waha:3000
      - AUTHENTICATION_API_KEY=THISISMYSECURETOKEN
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - ./:/app
    depends_on:
      - waha

  # WAHA (WhatsApp HTTP API)
  waha:
    image: devlikeapro/waha:latest
    container_name: chatbot_waha
    restart: always
    ports:
      - "3000:3000"
    environment:
      - WAHA_API_KEY=THISISMYSECURETOKEN
      - WAHA_WORKER_ID=default
      - WHATSAPP_DEFAULT_ENGINE=WEBJS
    volumes:
      - waha_data:/app/.waha

volumes:
  waha_data:
