[build]
  base = "frontend"
  publish = "dist"
  command = "npm run build"

# Proxy para o Backend (Railway)
[[redirects]]
  from = "/api/*"
  to = "https://chatbot-production-e324.up.railway.app/:splat"
  status = 200
  force = true

# Redirecionamento para SPA (React) - IMPORTANTE
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
